import {calculate,identify,initialSettings} from './payroll.mjs';
import {initializeExperience} from './experience.js';
const $=s=>document.querySelector(s),form=$('#worker-form'),settingsForm=$('#settings-form');
let records=[],editing=null,settings={...initialSettings},noticeTimer;
const cash=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v);
const escapeText=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const el=n=>form.elements.namedItem(n);
const yn=(name,label)=>`<label>${label}<select name="${name}"><option value="unknown">Por confirmar</option><option value="yes">Sí</option><option value="no">No</option></select></label>`;
form.insertAdjacentHTML('afterbegin',`<div class="relationship-box"><label>Modalidad declarada<select name="relationship"><option value="labor">Contrato individual de trabajo</option><option value="services">Prestación de servicios / honorarios</option></select></label><details class="identify"><summary>Identificar la relación contractual</summary><p>Responde según lo que ocurre en la práctica, no solo por el título del contrato.</p><div class="fields">${yn('personal','¿La persona realiza el trabajo personalmente?')}${yn('subordinate','¿Existe dirección y subordinación?')}${yn('paid','¿Recibe remuneración por el trabajo?')}</div><div id="identification" class="classification" aria-live="polite">Completa las respuestas para obtener una orientación.</div><small>Orientación académica, no una calificación jurídica definitiva.</small></details></div>`);
el('gross').closest('label').firstChild.textContent='Salario base / honorarios mensuales ($)';
el('minimum').closest('label').insertAdjacentHTML('afterend',`<label>Categoría de salario mínimo<input name="category" maxlength="100" value="Comercio y servicios (ejemplo)"><small>El monto se introduce manualmente según categoría.</small></label><label>Bonos ordinarios ($)<input name="bonus" type="number" min="0" max="10000000" step="0.01" value="0" required></label><label>Comisiones ($)<input name="commission" type="number" min="0" max="10000000" step="0.01" value="0" required></label><label>Frecuencia de pago<select name="frequency"><option value="monthly">Mensual</option><option value="fortnight">Quincenal</option></select><small>Cálculos mensuales. Quincenal muestra dos mitades estimadas.</small></label><label>Método de pago<select name="method"><option>Transferencia bancaria</option><option>Efectivo</option><option>Cheque</option><option>Otro (verificar legalidad)</option></select></label>`);
$('.form-actions').insertAdjacentHTML('beforebegin',`<h3 class="section-label">Impuesto sobre la renta</h3><p class="muted">Introduce el ISR del mes ya calculado con la tabla o régimen aplicable. No se calcula automáticamente.</p><div class="fields"><label>Retención ISR mensual ($)<input name="tax" type="number" min="0" max="10000000" step="0.01" required value="0"></label><label>Validación del ISR<select name="taxStatus"><option value="no">Pendiente de validar</option><option value="yes">Monto validado (incluido cero)</option></select></label></div>`);
$('.receipt-line.total').insertAdjacentHTML('beforebegin',`<div class="receipt-line"><span>Base orientativa ISR <small>bruto − ISSS − AFP</small></span><span id="r-taxbase">—</span></div><div class="receipt-line"><span>ISR ingresado</span><span id="r-tax">—</span></div>`);
$('.net').insertAdjacentHTML('afterend',`<p class="receipt-note" id="payment-detail">Pago mensual</p><details class="employer"><summary>Aportes patronales · no se descuentan</summary><div class="receipt-line"><span>ISSS patronal <small>7.5%</small></span><span id="r-employer-isss">—</span></div><div class="receipt-line"><span>AFP patronal <small>8.75%</small></span><span id="r-employer-afp">—</span></div></details><p class="receipt-note" id="debt-reference"></p>`);
$('.settings p').textContent='ISSS 3% trabajador / 7.5% patrono y AFP 7.25% trabajador / 8.75% patrono, según el pizarrón. Tope ISSS de $1,000 como supuesto de demostración. La referencia de clase para deuda ordinaria es 20% del excedente sobre el mínimo. No verificados como normativa vigente. Confirma con la docente. Los cambios recalculan todos los registros de esta sesión.';
$('.settings-fields').insertAdjacentHTML('beforeend',`<label>ISSS patronal (%)<input name="employerIsss" type="number" min="0" max="100" step="0.01" value="7.5" required></label><label>AFP patronal (%)<input name="employerAfp" type="number" min="0" max="100" step="0.01" value="8.75" required></label><label>Referencia deuda ordinaria (%)<input name="debtLimit" type="number" min="0" max="100" step="0.01" value="20" required></label>`);
$('footer p').textContent='Modelo académico basado en las notas de clase, pendiente de validación normativa. Cálculos mensuales para ingresos ordinarios; ISR manual. La clasificación contractual es orientativa. El mínimo depende de categoría y jornada. La referencia de embargo de clase no reemplaza una orden ni el límite legal vigente. Las alertas no autorizan ni bloquean descuentos. Servicios especiales, IVA y otros tributos no incluidos.';
$('.period span').textContent='Base mensual · USD';
$('thead tr').innerHTML='<th>Persona / contrato</th><th>Bruto</th><th>ISSS</th><th>AFP</th><th>ISR</th><th>Alimentos</th><th>Otros</th><th>Líquido</th><th>Revisión</th><th>Acciones</th>';
$('.payroll .panel-head h2').textContent='Planilla de trabajadores y servicios';
function read(){const d={};for(const [k,v]of new FormData(form))d[k]=v;for(const k of ['gross','minimum','food','debt','bonus','commission','tax'])d[k]=Number(d[k]);d.isss=el('isss').checked;d.afp=el('afp').checked;return d;}
function valid(d){return ['gross','minimum','food','debt','bonus','commission','tax'].every(k=>Number.isFinite(d[k])&&d[k]>=0&&d[k]<=10000000)&&d.minimum>0;}
function mode(){const labor=el('relationship').value==='labor';for(const n of ['isss','afp','isssState','afpState','type','minimum','category'])el(n).disabled=!labor;$('.contributions').classList.toggle('inactive',!labor);el('role').closest('label').firstChild.textContent=labor?'Cargo':'Servicio realizado';$('.net>span').textContent=labor?'Salario líquido':'Honorarios netos';}
function current(){const d=read();if(d.relationship==='services'){d.minimum=Number(el('minimum').value)||408.8;d.type='Servicios';d.category='No aplica';}return d;}
function renderLive(){mode();const d=current(),r=calculate(d,settings),hasAmount=el('gross').value!==''&&valid(d);const ids={gross:r.gross,isss:r.isss,afp:r.afp,food:d.food,debt:d.debt,deductions:r.deductions,net:r.net,tax:d.tax,taxbase:r.taxBase,'employer-isss':r.employerIsss,'employer-afp':r.employerAfp};for(const [k,v]of Object.entries(ids))$('#r-'+k).textContent=hasAmount?cash(v):'—';$('#isss-rate').textContent=settings.isssRate+'%';$('#afp-rate').textContent=settings.afpRate+'%';$('.employer .receipt-line:nth-of-type(1) small').textContent=settings.employerIsss+'%';$('.employer .receipt-line:nth-of-type(2) small').textContent=settings.employerAfp+'%';$('#payment-detail').textContent=d.frequency==='fortnight'?'Dos pagos orientativos: '+(hasAmount?cash(Math.floor(r.net*50)/100)+' y '+cash(r.net-Math.floor(r.net*50)/100):'—')+'. No es cálculo fiscal quincenal.':'Pago mensual · '+d.method;$('#debt-reference').textContent=d.relationship==='labor'&&d.debtType==='ordinary'&&hasAmount?'Referencia de clase para deuda: '+cash(r.limit)+' ('+settings.debtLimit+'% del excedente sobre '+cash(d.minimum)+').':'';$('#identification').textContent=r.identification==='labor'?'Indicios de contrato individual de trabajo: servicio personal, remuneración y subordinación.':r.identification==='services'?'Posible prestación de servicios independiente: se declara ausencia de subordinación. Confirmar condiciones reales.':'Información insuficiente: completa las tres respuestas. No se determina solo por el nombre del contrato.';$('#alert-count').textContent=hasAmount?r.alerts.length:'0';$('#alerts').innerHTML=!hasAmount?'<p class="muted">Introduce importes válidos para revisar las alertas.</p>':r.alerts.length?r.alerts.map(a=>`<div class="alert ${a.level==='error'?'error':''}"><strong>ALERTA:</strong> ${escapeText(a.text)}</div>`).join(''):'<div class="alert ok">Sin alertas en los controles configurados. Esto no certifica cumplimiento legal.</div>';}
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#toast').hidden=true,3500);}
function renderRecords(){const totals={gross:0,deductions:0,net:0};for(const d of records){const r=calculate(d,settings);for(const k of Object.keys(totals))totals[k]+=r[k];}$('#count').textContent=records.length;$('#gross-total').textContent=cash(totals.gross);$('#ded-total').textContent=cash(totals.deductions);$('#net-total').textContent=cash(totals.net);$('#record-count').textContent=records.length+' registros · '+(records.some(d=>d.relationship==='services')&&records.some(d=>d.relationship==='labor')?'Mixta':'Única');$('#empty').hidden=records.length>0;$('#table-wrap').hidden=!records.length;$('#rows').innerHTML=records.map(d=>{const r=calculate(d,settings);return `<tr><td><strong>${escapeText(d.name)}</strong><small>${escapeText(d.role)} · ${d.relationship==='labor'?'Individual / '+escapeText(d.type):'Servicios'}</small><small>${d.frequency==='fortnight'?'Quincenal':'Mensual'} · ${escapeText(d.method)}</small></td>${[r.gross,r.isss,r.afp,d.tax,d.food,d.debt,r.net].map(n=>`<td>${cash(n)}</td>`).join('')}<td>${r.alerts.length?`<details><summary class="status-alert">${r.alerts.length} alertas</summary>${r.alerts.map(a=>`<p>${escapeText(a.text)}</p>`).join('')}</details>`:'<span class="status-ok">Sin alertas</span>'}</td><td><button type="button" data-edit="${d.id}">Editar</button><button type="button" class="delete" data-delete="${d.id}">Eliminar</button></td></tr>`;}).join('');}
function reset(){HTMLFormElement.prototype.reset.call(form);editing=null;$('#form-title').textContent='Datos del trabajador';$('#submit-button').textContent='Agregar a la planilla ＋';$('#form-error').textContent='';renderLive();}
form.addEventListener('input',()=>renderLive());form.addEventListener('change',()=>renderLive());
form.addEventListener('submit',e=>{e.preventDefault();const d=current();d.name=d.name.trim();d.role=d.role.trim();if(!valid(d)||!d.name||!d.role){$('#form-error').textContent='Completa nombre, cargo o servicio e importes válidos.';return;}if(editing){const index=records.findIndex(x=>x.id===editing);records[index]={...d,id:editing};}else records.push({...d,id:crypto.randomUUID()});renderRecords();reset();toast('Registro agregado o actualizado. Revisa las alertas antes de realizar pagos.');});
$('#reset').addEventListener('click',reset);$('#example').addEventListener('click',()=>{reset();const demo={name:'Ana Martínez (ejemplo)',role:'Auxiliar administrativa',gross:600,minimum:408.8,food:0,debt:0,bonus:25,commission:0,personal:'yes',subordinate:'yes',paid:'yes',isssState:'paid',afpState:'paid'};for(const[k,v]of Object.entries(demo))el(k).value=v;renderLive();toast('Ejemplo ficticio cargado; aún no está en la planilla.');});
$('#rows').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.edit){const d=records.find(x=>x.id===b.dataset.edit);reset();el('relationship').value=d.relationship;mode();for(const[k,v]of Object.entries(d)){const field=el(k);if(field){if(field.type==='checkbox')field.checked=v;else field.value=v;}}editing=d.id;$('#form-title').textContent='Editar registro';$('#submit-button').textContent='Guardar cambios';renderLive();form.scrollIntoView({behavior:'smooth',block:'start'});el('name').focus({preventScroll:true});}if(b.dataset.delete&&confirm('¿Eliminar este registro de la planilla de esta sesión?')){records=records.filter(x=>x.id!==b.dataset.delete);if(editing===b.dataset.delete)reset();renderRecords();toast('Registro eliminado.');}});
settingsForm.addEventListener('submit',e=>{e.preventDefault();const next=Object.fromEntries([...new FormData(settingsForm)].map(([k,v])=>[k,Number(v)]));if(Object.values(next).some(v=>!Number.isFinite(v)||v<0))return;settings=next;renderLive();renderRecords();toast('Parámetros aplicados a toda la planilla.');});
// The same classification used by the visible questionnaire is available to compatible agents.
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'orientar_relacion_contractual',title:'Orientar relación contractual',description:'Completa el cuestionario visible y devuelve una orientación académica. No crea registros ni determina legalidad.',inputSchema:{type:'object',properties:{personal:{type:'string',enum:['yes','no','unknown']},subordinate:{type:'string',enum:['yes','no','unknown']},paid:{type:'string',enum:['yes','no','unknown']}},required:['personal','subordinate','paid'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){for(const key of ['personal','subordinate','paid'])if(!['yes','no','unknown'].includes(input?.[key]))throw new Error('Respuesta inválida');for(const key of ['personal','subordinate','paid'])el(key).value=input[key];$('.identify').open=true;renderLive();return{orientation:identify(input),notice:'Orientación académica, no calificación jurídica definitiva.'};}})).catch(()=>{});}catch{}}
// Clear automatic contribution cards; payment status is independent from withholding.
$('h1').textContent='Tu planilla, paso a paso';
$('.sub').textContent='Registra los ingresos. Revisa los descuentos. Confirma el líquido.';
$('.heading').insertAdjacentHTML('afterend','<nav class="steps" aria-label="Secciones de la planilla"><a href="#worker-form"><b>1</b> Datos e ingresos</a><a href="#deduction-controls"><b>2</b> Deducciones</a><a href="#payroll-list"><b>3</b> Planilla</a></nav>');
$('.contributions').id='deduction-controls';$('.payroll').id='payroll-list';
for(const name of ['isss','afp']){
 const control=el(name),label=control.closest('label');control.type='hidden';control.value='automatic';
 label.className='auto-title';label.childNodes.forEach(node=>{if(node.nodeType===3)node.textContent='';});
 label.insertAdjacentHTML('beforeend',`<span>${name.toUpperCase()}</span><span class="auto-pill">Automático</span>`);
 label.insertAdjacentHTML('afterend',`<div class="auto-amount"><strong id="auto-${name}-amount">—</strong><span id="auto-${name}-rate"></span></div><p class="auto-base" id="auto-${name}-base"></p>`);
 const state=el(name+'State');state.closest('label').firstChild.textContent='Pago a '+name.toUpperCase();
 state.querySelector('[value="paid"]').textContent='Pagado a la institución';state.querySelector('[value="pending"]').textContent='Pendiente de pago';state.querySelector('[value="unknown"]').textContent='Sin confirmar';
}
$('.contributions').insertAdjacentHTML('beforebegin','<p class="muted auto-help">El descuento se calcula al escribir el salario. El estado de pago solo indica si fue entregado a la institución.</p>');
el('debt').closest('label').firstChild.textContent='Otros descuentos solicitados ($)';
el('authorization').closest('label').insertAdjacentHTML('beforeend','<small id="debt-help">Solo se aplican al elegir el tipo y confirmar el fundamento o autorización.</small>');
el('food').closest('label').insertAdjacentHTML('beforeend','<small>Ingresa el importe de la orden. Su equivalente porcentual aparecerá en la revisión.</small>');
$('.receipt').insertAdjacentHTML('afterbegin','<span class="calculation-badge" id="calculation-status">Completa los ingresos</span>');
$('.receipt .net').insertAdjacentHTML('afterend','<p class="receipt-note" id="effective-deduction"></p>');
$('.alerts-panel').insertAdjacentHTML('afterbegin','<p class="review-help">Primero resuelve los errores. Después confirma los pagos y datos pendientes.</p>');
$('footer p').textContent='Modelo académico con parámetros de clase, pendientes de validación normativa. ISSS y AFP automáticos en contrato individual; no cubre excepciones ni regímenes especiales. ISR manual hasta verificar la tabla. Las deudas sin tipo o fundamento confirmado no se aplican. La referencia del 20% no sustituye el límite legal ni una orden. Alimentos según importe ingresado. Datos temporales; no se efectúan pagos reales.';
$('.settings summary').firstChild.textContent='Tasas y reglas del ejercicio ';
const previousLive=renderLive;
renderLive=function(){
 previousLive();
 const d=current(),r=calculate(d,settings),ready=el('gross').value!==''&&valid(d),labor=d.relationship==='labor';
 for(const name of ['isss','afp']){
  el(name).disabled=true;
  const base=name==='isss'?Math.min(r.gross,settings.isssCap):r.gross;
  $('#auto-'+name+'-amount').textContent=ready?cash(r[name]):'—';
  $('#auto-'+name+'-rate').textContent=labor?settings[name+'Rate']+'% del trabajador':'No aplica en este modelo';
  $('#auto-'+name+'-base').textContent=labor?(ready?'Base: '+cash(base)+'. ':'')+(name==='isss'?'Tope mensual del descuento: '+cash(settings.isssCap*settings.isssRate/100):'El aporte patronal se muestra aparte.'):'Prestación de servicios: revisa el régimen correspondiente.';
 }
 $('#r-debt').textContent=ready?cash(r.appliedDebt):'—';
 $('#debt-help').textContent=d.debt>0&&r.appliedDebt===0?'Pendiente: el importe solicitado no se descuenta hasta indicar tipo y fundamento.':'Importe aplicado: '+cash(r.appliedDebt)+'. Confirma el documento que lo respalda.';
 const percent=r.gross>0?(r.deductions/r.gross*100).toFixed(2)+'%':'—';
 $('#effective-deduction').textContent=ready?'Deducciones aplicadas: '+percent+' del ingreso bruto.':'';
 const errors=r.alerts.filter(a=>a.level==='error'),pending=r.alerts.filter(a=>a.level!=='error');
 $('#calculation-status').textContent=!ready?'Completa los ingresos':errors.length?'Revisar '+errors.length+' errores':d.taxStatus!=='yes'?'Líquido provisional · validar ISR':'Cálculo actualizado';
 $('#calculation-status').classList.toggle('needs-review',ready&&(errors.length>0||d.taxStatus!=='yes'));
 if(ready){
  const cards=list=>list.map(a=>`<div class="alert ${a.level==='error'?'error':''}"><strong>ALERTA:</strong> ${escapeText(a.text)}</div>`).join('');
  $('#alerts').innerHTML=(errors.length?'<h3 class="review-group">Requiere corrección</h3>'+cards(errors):'')+(pending.length?`<details class="pending-review" open><summary>${pending.length} controles por revisar</summary>${cards(pending)}</details>`:'')+(!r.alerts.length?'<div class="alert ok">Sin alertas en los controles configurados. Esto no certifica cumplimiento legal.</div>':'');
 }
};
const previousRecords=renderRecords;
renderRecords=function(){previousRecords();document.querySelectorAll('#rows tr').forEach((row,index)=>{const r=calculate(records[index],settings);row.cells[6].textContent=cash(r.appliedDebt);row.cells[7].classList.add('net-cell');row.querySelector('[data-edit]').setAttribute('aria-label','Editar '+records[index].name);row.querySelector('[data-delete]').setAttribute('aria-label','Eliminar '+records[index].name);});};
window.addEventListener('beforeunload',e=>{if(records.length){e.preventDefault();e.returnValue='';}});renderLive();renderRecords();
initializeExperience({form,calculate,current,getSettings:()=>settings,formatMoney:cash});
